### Registe

POST http://localhost:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Test User",
    "email": "neo23@gmail.com",
    "telephone": "+1234567890",
    "password": "123456",
    "local": "Rua Exemplo, 123"
}

### Teste de Login

POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "neo23@gmail.com",
    "password": "123456"
}

###teste asdhyadhga

GET http://localhost:8000/api/user
Content-Type: application/json
Accept: application/json

### Criar item (assumindo categoria_id = 1)
POST http://localhost:8000/api/items
Content-Type: application/json
Accept: application/json

{
  "name": "Cadernoasd 2 Espiral",
  "description": "Capa dura, 200 folhas",
  "expiry_date": "2025-12-31",
  "category_id":"3" 
}

### Listar todos os itens
GET http://localhost:8000/api/items
Accept: application/json

### Listar itens de categorias diferentes
GET http://localhost:8000/api/categorias/1
Accept: application/json

###

### Ver item específico (substitua o ID se necessário)
GET http://localhost:8000/api/items/1
Accept: application/json

###

### Atualizar item (ID 1 como exemplo)
PUT http://localhost:8000/api/items/1
Content-Type: application/json

{
  "name": "Caderno Espiral",
  "price": 20.50
}

###

### Deletar item (ID 1 como exemplo)
DELETE http://localhost:8000/api/items/1
Accept: application/json