### Registe

POST http://localhost:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Test User",
    "email": "franci12sc1wo@example.com",
    "telephone": "+1234567890",
    "password": "password123"
}

### Teste de Login

POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "neo23@gmail.com",
    "password": "123456"
}

### Criar item (assumindo categoria_id = 1)
POST http://localhost:8000/api/items
Content-Type: application/json
Accept: application/json

{
  "name": "Caderno",
  "description": "Capa dura, 200 folhas",
  "price": "18.99",
  "category_id":"1" 
}

### Listar todos os itens
GET http://localhost:8000/api/items
Accept: application/json

###

### Ver item específico (substitua o ID se necessário)
GET http://localhost:8000/api/items/1
Accept: application/json

###

### Atualizar item (ID 1 como exemplo)
PUT http://localhost:8000/api/items/1
Content-Type: application/json

{
  "name": "Caderno Espiral",
  "price": 20.50
}

###

### Deletar item (ID 1 como exemplo)
DELETE http://localhost:8000/api/items/1
Accept: application/json